resources:
  - deployments/backend.yaml
  - deployments/database.yaml
  - services/loadBalancer.yaml
  - storage/pv.yaml
  - storage/pv-claim.yaml
  - configmaps/init-db.yaml

images:
  - name: k8s-multi-service-app
    newName: your-docker-hub-username/k8s-multi-service-app
    newTag: latest

secretGenerator:
  - name: database-creds
    literals:
      - username=postgres
      - password=postgres
