apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS requests (
      id SERIAL PRIMARY KEY,
      path TEXT,
      host TEXT,
      port INTEGER,
      time TEXT
    );
